[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.8"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[prune]
  go-tests = true
  unused-packages = true
